FROM node:16.14.2-alpine AS builder

RUN apk add --no-cache libc6-compat
RUN apk update
# Set working directory
WORKDIR /home
COPY . .

RUN npm install --registry=https://registry.npmmirror.com/  -g turbo@1.6.3
RUN npm run build_mode
RUN turbo prune --scope=lily-schedule --docker

# Add lockfile and package.json's of isolated subworkspace
FROM node:16.14.2-alpine AS installer
RUN apk add --no-cache libc6-compat
RUN apk update
WORKDIR /home

COPY --from=builder /home/out/json/ .
COPY --from=builder /home/out/package-lock.json ./package-lock.json
COPY .gitignore .gitignore
RUN npm install --registry=https://registry.npmmirror.com/ 

COPY turbo.json turbo.json
COPY --from=builder /home/out/full/ .
RUN npx turbo run build --filter=lily-schedule

FROM node:16.14.2-alpine AS runner
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
WORKDIR /home

# COPY --from=installer /home .

COPY --from=installer /home/turbo.json ./turbo.json
COPY --from=installer /home/node_modules ./node_modules
COPY --from=installer /home/package.json ./package.json
COPY --from=installer /home/package-lock.json ./package-lock.json
COPY --from=installer /home/packages ./packages
COPY --from=installer /home/apps/lily-schedule ./apps/lily-schedule

ENV TZ="Asia/Shanghai"

RUN npm install turbo@1.6.3  -g 
RUN npm install pm2 --registry=https://registry.npmmirror.com/  -g

EXPOSE 7001

ENTRYPOINT ["npm", "run", "online"]
